[package]
name = "chipr"
description = "A simple Chip-8 emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["gfx", "ttf"]
